namespace ASM.Constants
{
    public class SessionKey
    {
        public static class NguoiDung
        {
            public const string Username = "Username";
            public const string FullName = "FullName";
            public const string Validated = "Valid";
            public const string NguoidungContext = "NguoidungContext";
        }
       public static class KhachHang
        {
            public const string KH_Email = "KH_Email";
            public const string KH_FullName = "KH_FullName";
            public const string KH_Id = "KH_Id";
            public const string KH_Context = "KH_Context";
        }
    }
}
